# Generated by Django 4.2.10 on 2024-02-13 05:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_farmer_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='id_number',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(regex='^\\d+$')]),
        ),
    ]
