# Generated by Django 5.0.1 on 2024-02-01 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=15, unique=True)),
                ('description', models.TextField(max_length=500)),
                ('code', models.CharField(db_index=True, max_length=15, unique=True)),
            ],
            options={
                'verbose_name': 'Crop',
                'verbose_name_plural': 'Crops',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='FoodGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=20, unique=True)),
                ('description', models.TextField(max_length=500)),
                ('code', models.CharField(db_index=True, max_length=15, unique=True)),
            ],
            options={
                'verbose_name': 'Food Group',
                'verbose_name_plural': 'Food Groups',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='CropVariety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=30, unique=True)),
                ('code', models.CharField(db_index=True, max_length=15, unique=True)),
                ('crop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crops.crop')),
                ('food_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crops.foodgroup')),
            ],
            options={
                'verbose_name': 'Crop Variety',
                'verbose_name_plural': 'Crop Varieties',
                'ordering': ('name',),
            },
        ),
    ]
