# Generated by Django 5.0.1 on 2024-02-05 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CropJourney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(db_index=True, max_length=15, unique=True)),
                ('description', models.TextField()),
                ('crop_variety', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cropjournies', to='crops.cropvariety')),
            ],
            options={
                'verbose_name': 'Crop Journey',
                'verbose_name_plural': 'Crop Journies',
                'ordering': ('crop_variety', 'name'),
            },
        ),
        migrations.CreateModel(
            name='GrowthStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_number', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(db_index=True, max_length=15, unique=True)),
                ('description', models.TextField()),
                ('min_stage_duration', models.IntegerField(help_text='Days')),
                ('max_stage_duration', models.IntegerField(help_text='Days')),
                ('average_duration', models.IntegerField(editable=False)),
                ('crop_variety', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stages', to='crops.cropvariety')),
            ],
            options={
                'verbose_name': 'Growth Stage',
                'verbose_name_plural': 'Growth Stages',
                'ordering': ('crop_variety', 'stage_number'),
                'unique_together': {('crop_variety', 'stage_number')},
            },
        ),
        migrations.CreateModel(
            name='CropJourneyStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('crop_journey', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.cropjourney')),
                ('growth_stage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.growthstage')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='cropjourney',
            name='growth_stages',
            field=models.ManyToManyField(through='production.CropJourneyStage', to='production.growthstage'),
        ),
    ]
