# Generated by Django 5.0.1 on 2024-02-05 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cropjourneystage',
            options={'ordering': ['order'], 'verbose_name': 'Crop Journey Stage', 'verbose_name_plural': 'Crop Journey Stages'},
        ),
        migrations.AlterUniqueTogether(
            name='cropjourneystage',
            unique_together={('crop_journey', 'growth_stage')},
        ),
    ]
