# Generated by Django 4.2.10 on 2024-02-12 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_farmer_phone_number'),
        ('farm', '0003_watersource_location'),
        ('production', '0002_alter_cropjourneystage_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmingJourney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('completed', models.BooleanField(default=True)),
                ('successful', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('crop_journey', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='farming', to='production.cropjourney')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='land', to='farm.farm')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='farmers', to='profiles.farmer')),
            ],
            options={
                'verbose_name': 'Farming Journey',
                'verbose_name_plural': 'Farming Journies',
                'ordering': ['-timestamp'],
                'unique_together': {('crop_journey', 'farmer', 'farm', 'start_date')},
            },
        ),
    ]
