# Generated by Django 5.0.1 on 2024-02-02 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Soil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=15, unique=True)),
                ('texture', models.CharField(choices=[('sandy', 'sandy'), ('clay', 'clay'), ('silty', 'silty'), ('loamy', 'loamy')], max_length=20)),
                ('color', models.CharField(choices=[('brown', 'brown'), ('black', 'black'), ('red', 'red'), ('yellow', 'yellow')], max_length=20)),
                ('depth', models.IntegerField()),
                ('structure', models.CharField(max_length=50)),
                ('porosity', models.FloatField()),
                ('stone_content', models.FloatField()),
                ('acidity_level', models.CharField(choices=[('acidic', 'acidic'), ('neutral', 'neutral'), ('alkaline', 'alkaline')], max_length=20)),
                ('description', models.TextField(max_length=500)),
            ],
            options={
                'verbose_name': 'Soil',
                'verbose_name_plural': 'Soils',
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='WaterSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(db_index=True, max_length=15, unique=True)),
                ('water_type', models.CharField(choices=[('acidic', 'acidic'), ('salty', 'salty'), ('fresh', 'fresh')], max_length=20)),
                ('water_source_type', models.CharField(choices=[('dam', 'dam'), ('river', 'river'), ('well', 'well'), ('rain', 'rain'), ('other', 'other')], max_length=20)),
                ('is_seasonal', models.BooleanField(default=False)),
                ('water_capacity', models.DecimalField(decimal_places=2, help_text='Meters cubed', max_digits=10)),
                ('is_shared', models.BooleanField(default=True)),
                ('is_dry', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Water Source',
                'verbose_name_plural': 'Water Sources',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=15, unique=True)),
                ('size', models.DecimalField(decimal_places=2, help_text='Acres', max_digits=7)),
                ('slope', models.CharField(choices=[('flat', 'flat'), ('east', 'east'), ('west', 'west'), ('north', 'north'), ('south', 'south')], max_length=20)),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='farm.village')),
                ('soil', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='farm.soil')),
                ('water_source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='farm.watersource')),
            ],
            options={
                'verbose_name': 'Farm',
                'verbose_name_plural': 'Farms',
                'ordering': ('code',),
            },
        ),
    ]
