# Generated by Django 5.0.1 on 2024-02-05 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Input',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('code', models.CharField(db_index=True, max_length=15, unique=True)),
                ('description', models.TextField(max_length=500)),
                ('measuring_unit', models.CharField(choices=[('litres', 'litres'), ('kilograms', 'kilograms'), ('50kg bags', '50kg bags'), ('tonnes', 'tonnes')], max_length=20)),
            ],
            options={
                'verbose_name': 'Input',
                'verbose_name_plural': 'Inputs',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='InputCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('code', models.CharField(db_index=True, max_length=15, unique=True)),
                ('description', models.TextField(max_length=500)),
            ],
            options={
                'verbose_name': 'Input Category',
                'verbose_name_plural': 'Input Categories',
                'ordering': ('name',),
            },
        ),
    ]
